vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO bluequartzsoftware/ebsdlib
  REF "v${VERSION}"
  SHA512 05fc9c5e63e1ab1912f9db534371b58b66f2ad71284a089698fddefc268556ad64b41ac888c5607eaf465fbb853240b8834aab445a82f3017ad895bd2fbe0934
  HEAD_REF develop
)

set(EBSDLIB_COMMIT_HASH "98e8dad2d0f4c0eddda45d71a4a9d487f6b63482")

vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
  FEATURES
    hdf5      EbsdLib_ENABLE_HDF5
    parallel  EbsdLib_ENABLE_MULTICORE
)

vcpkg_cmake_configure(
  SOURCE_PATH "${SOURCE_PATH}"
  OPTIONS
    -DDREAM3D_ANACONDA=ON
    -DCMP_TBB_ENABLE_COPY_INSTALL=OFF
    -DEbsdLib_BUILD_TESTS=OFF
    -DEbsdLib_BUILD_TOOLS=OFF
    -DEbsdLib_BUILD_H5SUPPORT=OFF
    -DEbsdLib_CMAKE_CONFIG_INSTALL_DIR=share/${PORT}
    -DTBB_STATUS_PRINTED=ON
    -DGVS_GIT_HASH=${EBSDLIB_COMMIT_HASH}
    ${FEATURE_OPTIONS}
  MAYBE_UNUSED_VARIABLES
    CMP_TBB_ENABLE_COPY_INSTALL
    TBB_STATUS_PRINTED
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup()

vcpkg_copy_pdbs()

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")
